server:
  port: 8989
  context-path: /spring-boot-jsp
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: abc
    driver-class-name: oracle.jdbc.OracleDriver
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mvc:
    view:
      prefix: /
      suffix: .jsp


mybatis:
  type-aliases-package: com.baizhi.entity
